platform :ios, '10.0'

use_frameworks!
target 'Seeing' do
pod 'Reachability'
pod 'SnapKit', '~> 5.0.0'
pod 'Alamofire'
pod 'SwiftyJSON', '~> 4.0'
pod 'RxSwift', '6.1.0'
pod 'RxCocoa', '6.1.0'
pod 'Kingfisher', '~> 6.0'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'TXIMSDK_iOS'
pod 'TXLiteAVSDK_TRTC'
pod 'Toast-Swift', '5.0.0'
pod 'Material'
pod 'NVActivityIndicatorView'
end
